package dev.esgenius.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import dev.esgenius.entity.EsgCategory;
import dev.esgenius.entity.Framework;
import dev.esgenius.entity.FrameworkRequirement;
import dev.esgenius.entity.FrameworkStatus;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIf;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Offline smoke test against real Infosys extracted text downloaded from the running API.
 * Enabled only when {@code backend/target/infosys-document.json} is present.
 */
class InfosysBrsrRetrievalSmokeTest {

    private static final Path DOCUMENT_JSON = Path.of("target", "infosys-document.json");

    @Test
    @EnabledIf("infosysDocumentAvailable")
    void improvedRetrievalOnRealInfosysText() throws Exception {
        JsonNode document = new ObjectMapper().readTree(DOCUMENT_JSON.toFile());
        String extractedText = document.get("extractedText").asText();
        assertThat(extractedText).isNotBlank();

        Framework framework = new Framework("BRSR", "BRSR", "BRSR", "India", "MVP-2026", FrameworkStatus.ACTIVE);
        TextChunkingService chunkingService = new TextChunkingService();
        LexicalEvidenceRetrievalService retrievalService = new LexicalEvidenceRetrievalService();
        List<TextChunk> chunks = chunkingService.chunk(extractedText);

        assertThat(chunks.size()).isGreaterThan(10);

        List<FrameworkRequirement> requirements = List.of(
                req(framework, "ENV-001", "Total Energy Consumption", EsgCategory.ENVIRONMENTAL,
                        "Disclosure of total energy consumed from renewable and non-renewable sources with energy intensity ratios.",
                        "The entity shall disclose total energy consumed from all sources during the reporting period."),
                req(framework, "ENV-002", "Renewable vs Non-Renewable Energy Breakdown", EsgCategory.ENVIRONMENTAL,
                        "Split of energy consumption between renewable and non-renewable sources, reported separately for electricity, fuel and others.",
                        "The entity shall separately disclose the total energy consumed from renewable sources and from non-renewable sources."),
                req(framework, "ENV-003", "Scope 1 GHG Emissions", EsgCategory.ENVIRONMENTAL,
                        "Direct greenhouse gas emissions from owned or controlled sources.",
                        "The entity shall disclose total Scope 1 emissions in metric tonnes of CO2 equivalent."),
                req(framework, "ENV-004", "Scope 2 GHG Emissions", EsgCategory.ENVIRONMENTAL,
                        "Indirect emissions from purchased electricity, steam, heating and cooling.",
                        "The entity shall disclose total Scope 2 emissions in metric tonnes of CO2 equivalent."),
                req(framework, "ENV-005", "Scope 3 GHG Emissions", EsgCategory.ENVIRONMENTAL,
                        "Other indirect value-chain emissions across upstream and downstream categories.",
                        "The entity shall disclose Scope 3 emissions, covering material upstream and downstream value-chain categories."),
                req(framework, "ENV-006", "Water Withdrawal Disclosure", EsgCategory.ENVIRONMENTAL,
                        "Total water withdrawal segregated by source across operating locations.",
                        "The entity shall disclose total water withdrawal by source."),
                req(framework, "ENV-007", "Waste Recycling Data", EsgCategory.ENVIRONMENTAL,
                        "Waste generation and recovery quantities by waste category.",
                        "The entity shall disclose total waste generated by category and the quantity recovered through recycling."),
                req(framework, "SOC-001", "Employee Health & Safety", EsgCategory.SOCIAL,
                        "Occupational health and safety management system coverage and incidents.",
                        "The entity shall describe its occupational health and safety management system."),
                req(framework, "SOC-002", "Employee Training & Development Hours", EsgCategory.SOCIAL,
                        "Training and awareness programme coverage across the workforce.",
                        "The entity shall disclose training and awareness programmes with coverage by employee category and gender."),
                req(framework, "SOC-003", "Human Rights Due Diligence", EsgCategory.SOCIAL,
                        "Human rights due-diligence process, assessments and remediation.",
                        "The entity shall disclose the process for human rights due diligence."),
                req(framework, "SOC-004", "Community Development Spend", EsgCategory.SOCIAL,
                        "Community and CSR investment with beneficiary coverage.",
                        "The entity shall disclose CSR and community development expenditure."),
                req(framework, "GOV-001", "Anti-Corruption Policy", EsgCategory.GOVERNANCE,
                        "Anti-bribery and anti-corruption policy, coverage and enforcement.",
                        "The entity shall disclose whether an anti-corruption or anti-bribery policy exists."),
                req(framework, "GOV-002", "Board Composition & Independence", EsgCategory.GOVERNANCE,
                        "Composition, independence and diversity of the board of directors.",
                        "The entity shall disclose board composition, including independence and diversity of directors."),
                req(framework, "GOV-003", "Whistleblower Mechanism", EsgCategory.GOVERNANCE,
                        "Vigil mechanism availability, accessibility and complaint handling.",
                        "The entity shall disclose the existence of a vigil or whistleblower mechanism."));

        System.out.println("=== IMPROVED RETRIEVAL ON REAL INFOSYS BRSR ===");
        for (FrameworkRequirement requirement : requirements) {
            List<RetrievedChunk> results = retrievalService.retrieve(requirement, chunks);
            String top = results.isEmpty() ? "(no evidence)" : summarize(results.get(0).text());
            System.out.printf("%s | score=%.2f | %s%n",
                    requirement.getRequirementCode(),
                    results.isEmpty() ? 0.0 : results.get(0).score(),
                    top);
        }

        assertImprovedEvidence(retrievalService.retrieve(requirements.get(4), chunks), "scope 3");
        assertImprovedEvidence(retrievalService.retrieve(requirements.get(7), chunks), "occupational", "health", "safety");
        assertImprovedEvidence(retrievalService.retrieve(requirements.get(11), chunks), "anti", "corruption", "bribery");
        assertImprovedEvidence(retrievalService.retrieve(requirements.get(12), chunks), "independent");
        assertImprovedEvidence(retrievalService.retrieve(requirements.get(10), chunks), "csr", "expenditure", "spent", "section 135");

        List<RetrievedChunk> trainingResults = retrievalService.retrieve(requirements.get(8), chunks);
        if (!trainingResults.isEmpty()) {
            String top = trainingResults.get(0).text().toLowerCase();
            assertThat(top).doesNotContain("principles during the financial year");
            assertThat(top).containsAnyOf("training hours", "learning", "development", "employee training");
        }
    }

    static boolean infosysDocumentAvailable() {
        return Files.exists(DOCUMENT_JSON);
    }

    private void assertImprovedEvidence(List<RetrievedChunk> results, String... expectedTerms) {
        assertThat(results).isNotEmpty();
        String top = results.get(0).text().toLowerCase();
        boolean matched = false;
        for (String term : expectedTerms) {
            if (top.contains(term.toLowerCase())) {
                matched = true;
                break;
            }
        }
        assertThat(matched).isTrue();
    }

    private String summarize(String text) {
        String normalized = text.replaceAll("\\s+", " ").trim();
        return normalized.substring(0, Math.min(120, normalized.length()));
    }

    private FrameworkRequirement req(
            Framework framework,
            String code,
            String title,
            EsgCategory category,
            String description,
            String frameworkText) {
        return new FrameworkRequirement(framework, code, title, category, description, frameworkText, true, "MVP-2026");
    }
}
