-- V11: Persist gap-assessment PDF export history for the Reports page.
-- Compatible with PostgreSQL and H2 (PostgreSQL mode)

CREATE TABLE report_export (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id     BIGINT       NOT NULL,
    user_id         UUID,
    format          VARCHAR(20)  NOT NULL,
    size_bytes      BIGINT       NOT NULL,
    generated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_report_export_analysis
        FOREIGN KEY (analysis_id) REFERENCES compliance_analysis(id) ON DELETE CASCADE
);

CREATE INDEX idx_report_export_user_id_generated_at
    ON report_export (user_id, generated_at DESC);
