-- V1: Core ESG schema tables
-- Compatible with PostgreSQL and H2 (PostgreSQL mode)

CREATE TABLE organization (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    cin         VARCHAR(50),
    sector      VARCHAR(255),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE framework (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL UNIQUE,
    name        VARCHAR(100) NOT NULL,
    full_name   VARCHAR(255) NOT NULL,
    region      VARCHAR(100),
    version     VARCHAR(50),
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE framework_requirement (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    framework_id     BIGINT       NOT NULL,
    requirement_code VARCHAR(20)  NOT NULL,
    title            VARCHAR(255) NOT NULL,
    category         VARCHAR(20)  NOT NULL,
    description      TEXT,
    framework_text   TEXT,
    mandatory        BOOLEAN      NOT NULL DEFAULT TRUE,
    version          VARCHAR(50),

    CONSTRAINT fk_requirement_framework
        FOREIGN KEY (framework_id) REFERENCES framework(id),

    CONSTRAINT uq_requirement_code_framework
        UNIQUE (framework_id, requirement_code)
);
