-- V4: Seed 14 prototype BRSR requirements
-- NOTE: This is a representative subset of the BRSR framework used for the MVP prototype.
--       It does NOT constitute the complete official SEBI BRSR disclosure set (56+ requirements).

INSERT INTO framework_requirement (framework_id, requirement_code, title, category, description, framework_text, mandatory, version)
VALUES
  ((SELECT id FROM framework WHERE code = 'BRSR'), 'ENV-001', 'Total Energy Consumption', 'ENVIRONMENTAL',
   'Disclosure of total energy consumed from renewable and non-renewable sources with energy intensity ratios.',
   'The entity shall disclose total energy consumed from all sources during the reporting period, expressed in joules or multiples, along with energy intensity per rupee of turnover.',
   TRUE, 'MVP-2026'),

  ((SELECT id FROM framework WHERE code = 'BRSR'), 'ENV-002', 'Renewable vs Non-Renewable Energy Breakdown', 'ENVIRONMENTAL',
   'Split of energy consumption between renewable and non-renewable sources, reported separately for electricity, fuel and others.',
   'The entity shall separately disclose the total energy consumed from renewable sources and from non-renewable sources during the reporting period, including electricity, fuel and other sources, with corresponding intensity ratios.',
   TRUE, 'MVP-2026'),

  ((SELECT id FROM framework WHERE code = 'BRSR'), 'ENV-003', 'Scope 1 GHG Emissions', 'ENVIRONMENTAL',
   'Direct greenhouse gas emissions from owned or controlled sources.',
   'The entity shall disclose total Scope 1 emissions in metric tonnes of CO2 equivalent, along with the methodology and emission factors used.',
   TRUE, 'MVP-2026'),

  ((SELECT id FROM framework WHERE code = 'BRSR'), 'ENV-004', 'Scope 2 GHG Emissions', 'ENVIRONMENTAL',
   'Indirect emissions from purchased electricity, steam, heating and cooling.',
   'The entity shall disclose total Scope 2 emissions in metric tonnes of CO2 equivalent, specifying whether a location-based or market-based method is used.',
   TRUE, 'MVP-2026'),

  ((SELECT id FROM framework WHERE code = 'BRSR'), 'ENV-005', 'Scope 3 GHG Emissions', 'ENVIRONMENTAL',
   'Other indirect value-chain emissions across upstream and downstream categories.',
   'The entity shall disclose Scope 3 emissions, covering material upstream and downstream value-chain categories, together with the categories considered and the basis of estimation.',
   TRUE, 'MVP-2026'),

  ((SELECT id FROM framework WHERE code = 'BRSR'), 'ENV-006', 'Water Withdrawal Disclosure', 'ENVIRONMENTAL',
   'Total water withdrawal segregated by source across operating locations.',
   'The entity shall disclose total water withdrawal by source, including surface water, groundwater, third-party water and others.',
   TRUE, 'MVP-2026'),

  ((SELECT id FROM framework WHERE code = 'BRSR'), 'ENV-007', 'Waste Recycling Data', 'ENVIRONMENTAL',
   'Waste generation and recovery quantities by waste category.',
   'The entity shall disclose total waste generated by category and the quantity recovered through recycling, reuse and other recovery operations.',
   TRUE, 'MVP-2026'),

  ((SELECT id FROM framework WHERE code = 'BRSR'), 'SOC-001', 'Employee Health & Safety', 'SOCIAL',
   'Occupational health and safety management system coverage and incidents.',
   'The entity shall describe its occupational health and safety management system, its coverage and details of safety-related incidents during the year.',
   TRUE, 'MVP-2026'),

  ((SELECT id FROM framework WHERE code = 'BRSR'), 'SOC-002', 'Employee Training & Development Hours', 'SOCIAL',
   'Training and awareness programme coverage across the workforce.',
   'The entity shall disclose training and awareness programmes with coverage by employee category and gender.',
   FALSE, 'MVP-2026'),

  ((SELECT id FROM framework WHERE code = 'BRSR'), 'SOC-003', 'Human Rights Due Diligence', 'SOCIAL',
   'Human rights due-diligence process, assessments and remediation.',
   'The entity shall disclose the process for human rights due diligence, assessments carried out during the year and remediation actions taken.',
   TRUE, 'MVP-2026'),

  ((SELECT id FROM framework WHERE code = 'BRSR'), 'SOC-004', 'Community Development Spend', 'SOCIAL',
   'Community and CSR investment with beneficiary coverage.',
   'The entity shall disclose CSR and community development expenditure along with the beneficiary areas covered.',
   FALSE, 'MVP-2026'),

  ((SELECT id FROM framework WHERE code = 'BRSR'), 'GOV-001', 'Anti-Corruption Policy', 'GOVERNANCE',
   'Anti-bribery and anti-corruption policy, coverage and enforcement.',
   'The entity shall disclose whether an anti-corruption or anti-bribery policy exists, its coverage and details of disciplinary actions taken during the year.',
   TRUE, 'MVP-2026'),

  ((SELECT id FROM framework WHERE code = 'BRSR'), 'GOV-002', 'Board Composition & Independence', 'GOVERNANCE',
   'Composition, independence and diversity of the board of directors.',
   'The entity shall disclose board composition, including independence and diversity of directors.',
   TRUE, 'MVP-2026'),

  ((SELECT id FROM framework WHERE code = 'BRSR'), 'GOV-003', 'Whistleblower Mechanism', 'GOVERNANCE',
   'Vigil mechanism availability, accessibility and complaint handling.',
   'The entity shall disclose the existence of a vigil or whistleblower mechanism, its accessibility to stakeholders and complaints received during the year.',
   TRUE, 'MVP-2026');
