-- V5: Add ESG rating, key issues, and events schema
-- Extends organization table with comparison fields
-- Adds ESG rating snapshots, key issues, company assessments, and events

-- Extend organization table with ticker and industry
ALTER TABLE organization ADD COLUMN IF NOT EXISTS ticker VARCHAR(20);
ALTER TABLE organization ADD COLUMN IF NOT EXISTS industry VARCHAR(255);

-- ESG Rating Snapshot table
CREATE TABLE IF NOT EXISTS esg_rating_snapshot (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id        BIGINT        NOT NULL,
    overall_score          DOUBLE PRECISION NOT NULL,
    environmental_score    DOUBLE PRECISION NOT NULL,
    social_score           DOUBLE PRECISION NOT NULL,
    governance_score       DOUBLE PRECISION NOT NULL,
    rating_band            VARCHAR(10)   NOT NULL,
    assessment_date        DATE          NOT NULL,
    previous_overall_score DOUBLE PRECISION,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_snapshot_organization
        FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE INDEX idx_esg_rating_snapshot_org_date
    ON esg_rating_snapshot(organization_id, assessment_date DESC);

-- ESG Key Issue table
CREATE TABLE IF NOT EXISTS esg_key_issue (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(100) NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    pillar      VARCHAR(20)  NOT NULL,
    description TEXT
);

CREATE INDEX idx_esg_key_issue_pillar
    ON esg_key_issue(pillar);

-- Company Key Issue Assessment table
CREATE TABLE IF NOT EXISTS company_key_issue_assessment (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id  BIGINT        NOT NULL,
    key_issue_id     BIGINT        NOT NULL,
    score            DOUBLE PRECISION NOT NULL,
    risk_level       VARCHAR(20)   NOT NULL,
    assessment_date  DATE          NOT NULL,

    CONSTRAINT fk_assessment_organization
        FOREIGN KEY (organization_id) REFERENCES organization(id),
    CONSTRAINT fk_assessment_key_issue
        FOREIGN KEY (key_issue_id) REFERENCES esg_key_issue(id)
);

CREATE INDEX idx_assessment_org_date
    ON company_key_issue_assessment(organization_id, assessment_date);

-- ESG Event table
CREATE TABLE IF NOT EXISTS esg_event (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT         NOT NULL,
    title         VARCHAR(255)    NOT NULL,
    description   TEXT,
    pillar        VARCHAR(20)     NOT NULL,
    key_issue_id  BIGINT,
    severity      VARCHAR(20)     NOT NULL,
    event_date    DATE            NOT NULL,
    score_impact  DOUBLE PRECISION,
    source_name   VARCHAR(255),
    source_url    TEXT,
    is_prototype  BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_event_organization
        FOREIGN KEY (organization_id) REFERENCES organization(id),
    CONSTRAINT fk_event_key_issue
        FOREIGN KEY (key_issue_id) REFERENCES esg_key_issue(id)
);

CREATE INDEX idx_esg_event_org_date
    ON esg_event(organization_id, event_date DESC);
CREATE INDEX idx_esg_event_severity
    ON esg_event(severity);
