-- V7: Uploaded document metadata and extracted text
-- Compatible with PostgreSQL and H2 (PostgreSQL mode)

CREATE TABLE document (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id     BIGINT       NOT NULL,
    original_filename   VARCHAR(255) NOT NULL,
    stored_filename     VARCHAR(255) NOT NULL,
    document_type       VARCHAR(50)  NOT NULL,
    reporting_year      INTEGER,
    status              VARCHAR(20)  NOT NULL,
    file_size           BIGINT       NOT NULL,
    page_count          INTEGER,
    storage_path        VARCHAR(512) NOT NULL,
    extracted_text      TEXT,
    uploaded_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at        TIMESTAMP WITH TIME ZONE,
    failure_reason      TEXT,

    CONSTRAINT fk_document_organization
        FOREIGN KEY (organization_id) REFERENCES organization(id),

    CONSTRAINT uq_document_stored_filename
        UNIQUE (stored_filename)
);

CREATE INDEX idx_document_organization_id ON document (organization_id);
CREATE INDEX idx_document_status ON document (status);
CREATE INDEX idx_document_uploaded_at ON document (uploaded_at DESC);
