-- V8: Compliance analysis and requirement-level evidence retrieval
-- Compatible with PostgreSQL and H2 (PostgreSQL mode)

CREATE TABLE compliance_analysis (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id     BIGINT       NOT NULL,
    framework_id    BIGINT       NOT NULL,
    status          VARCHAR(30)  NOT NULL,
    started_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at    TIMESTAMP WITH TIME ZONE,
    failure_reason  TEXT,

    CONSTRAINT fk_compliance_analysis_document
        FOREIGN KEY (document_id) REFERENCES document(id) ON DELETE CASCADE,
    CONSTRAINT fk_compliance_analysis_framework
        FOREIGN KEY (framework_id) REFERENCES framework(id)
);

CREATE INDEX idx_compliance_analysis_document_id ON compliance_analysis (document_id);
CREATE INDEX idx_compliance_analysis_framework_id ON compliance_analysis (framework_id);
CREATE INDEX idx_compliance_analysis_status ON compliance_analysis (status);

CREATE TABLE requirement_assessment (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id             BIGINT         NOT NULL,
    framework_requirement_id BIGINT        NOT NULL,
    assessment_status       VARCHAR(30)    NOT NULL,
    confidence              DOUBLE PRECISION,
    evidence_text           TEXT,
    evidence_chunks         TEXT,
    explanation             TEXT,
    gap                     TEXT,
    recommendation          TEXT,
    retrieval_score         DOUBLE PRECISION,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_requirement_assessment_analysis
        FOREIGN KEY (analysis_id) REFERENCES compliance_analysis(id) ON DELETE CASCADE,
    CONSTRAINT fk_requirement_assessment_requirement
        FOREIGN KEY (framework_requirement_id) REFERENCES framework_requirement(id),

    CONSTRAINT uq_requirement_assessment_analysis_requirement
        UNIQUE (analysis_id, framework_requirement_id)
);

CREATE INDEX idx_requirement_assessment_analysis_id ON requirement_assessment (analysis_id);
CREATE INDEX idx_requirement_assessment_requirement_id ON requirement_assessment (framework_requirement_id);
