-- V9: Per-page extracted text for page-aware evidence provenance
-- Compatible with PostgreSQL and H2 (PostgreSQL mode)

CREATE TABLE document_page (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id     BIGINT  NOT NULL,
    page_number     INTEGER NOT NULL,
    extracted_text  TEXT,

    CONSTRAINT fk_document_page_document
        FOREIGN KEY (document_id) REFERENCES document(id) ON DELETE CASCADE,

    CONSTRAINT uq_document_page_document_page_number
        UNIQUE (document_id, page_number)
);

CREATE INDEX idx_document_page_document_id ON document_page (document_id);
