import { createFileRoute, Link } from "@tanstack/react-router";
import { FileBarChart2, Eye, Download, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { AppLayout } from "@/components/app-layout";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { ORG, generatedReports, reportTemplates } from "@/lib/esg-data";

export const Route = createFileRoute("/reports/")({
  head: () => ({
    meta: [
      { title: "ESG Reports | ESGenius" },
      {
        name: "description",
        content:
          "Generate ESG gap assessment, environmental summary and executive sustainability reports from evidence-linked analysis.",
      },
      { property: "og:title", content: "ESG Reports | ESGenius" },
      {
        property: "og:description",
        content: "Report templates and previously generated ESG compliance documents.",
      },
    ],
  }),
  component: Reports,
});

function Reports() {
  return (
    <AppLayout
      title="Reports"
      description={`${ORG.name} · ${ORG.framework} · ${ORG.reportingPeriod}`}
    >
      <div className="grid gap-4 md:grid-cols-2">
        {reportTemplates.map((t) => (
          <article key={t.id} className="surface-card flex flex-col p-5">
            <div className="flex items-start gap-3">
              <span className="flex size-10 items-center justify-center rounded-lg bg-accent text-accent-foreground">
                <FileBarChart2 className="size-5" />
              </span>
              <div>
                <h2 className="font-semibold">{t.name}</h2>
                <p className="text-xs text-muted-foreground">Approx. {t.pages} pages · PDF</p>
              </div>
            </div>
            <p className="mt-3 flex-1 text-sm leading-relaxed text-muted-foreground">
              {t.description}
            </p>
            <div className="mt-4 flex flex-wrap gap-2">
              <Button onClick={() => toast.success(`${t.name} generated`)}>
                <Sparkles className="size-4" /> Generate Report
              </Button>
              {t.id === "gap-assessment" ? (
                <Button variant="outline" asChild>
                  <Link to="/reports/gap-assessment">
                    <Eye className="size-4" /> Preview
                  </Link>
                </Button>
              ) : (
                <Button variant="outline" onClick={() => toast("Preview coming soon")}>
                  <Eye className="size-4" /> Preview
                </Button>
              )}
              <Button variant="ghost" onClick={() => toast("Download started")}>
                <Download className="size-4" /> Download PDF
              </Button>
            </div>
          </article>
        ))}
      </div>

      <div className="surface-card mt-4 overflow-hidden">
        <div className="border-b border-border px-5 py-3">
          <p className="text-sm font-semibold">Previously Generated Reports</p>
        </div>
        <div className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow className="bg-muted/50">
                <TableHead>Report ID</TableHead>
                <TableHead>Report</TableHead>
                <TableHead>Reporting Period</TableHead>
                <TableHead>Generated</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Format</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {generatedReports.map((r) => (
                <TableRow key={r.id}>
                  <TableCell className="font-mono text-xs text-muted-foreground">{r.id}</TableCell>
                  <TableCell className="font-medium">{r.name}</TableCell>
                  <TableCell className="text-muted-foreground">{r.period}</TableCell>
                  <TableCell className="text-muted-foreground">{r.generated}</TableCell>
                  <TableCell className="text-muted-foreground">{r.generatedBy}</TableCell>
                  <TableCell className="text-muted-foreground">
                    {r.format} · {r.size}
                  </TableCell>
                  <TableCell>
                    <div className="flex justify-end gap-1">
                      <Button variant="ghost" size="sm" asChild>
                        <Link to="/reports/gap-assessment">
                          <Eye className="size-4" /> Preview
                        </Link>
                      </Button>
                      <Button variant="ghost" size="sm" onClick={() => toast("Download started")}>
                        <Download className="size-4" /> PDF
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      </div>
    </AppLayout>
  );
}
